# Enables floating item rotation.
enableFloatingItemRotation: true
# Enables the hotbar selector animation.
enableHotbarSelectorAnimation: true
# Enables hovering of matching items.
enableMatchingItemHovering: true
# Enables particles for rare items.
enableRarityParticles: true
# Enables vanilla slot highlighting
enableVanillaSlotHighlighting: true
# Affects the easing speed, that is applied to the rotation of the floating item.
floatingItemEasingSpeed: 0.75
# Affects the rotation amplitude of the floating item.
floatingItemRotationAmplitude: 1.0
# Affects the speed of the hotbar selector.
hotbarSelectorSpeed: 3.0
# Affects the size of the hovered item.
hoveredItemScale: 1.4
# Affects the hover amplitude of items, that match to the item that is carried in the cursor.
matchingItemHoverAmplitude: 0.8
# Moves the hotbar selector above the items. You might want to disable this, if you use resource packs that change the default selector texture.
renderHotbarSelectorAboveItems: false
