# Use Cloth Config mod for the descriptions.
---
contributorCosmetic: ''
globalTooltip: false
noMicrosoftTelemetry: true
debug:
  tagsTooltip: true
  debugTooltipMsg: true
  tagsTooltipAppendKeybindHint: true
  tagsPerPage: 6
  NBTTooltip: true
suppressExperimentalSettingsWarning: false
